package collector

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"log/slog"
	"net"
	"os"
	"strings"
	"sync/atomic"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"

	"kernelwatch/internal/config"
	"kernelwatch/internal/container"
)

// Event types — must match EVENT_* constants in tracer.c
const (
	EventExecve  = 1
	EventOpen    = 2
	EventConnect = 3
	EventClone   = 4
	EventPtrace  = 5
	EventModule  = 6
	EventBPF     = 7
)

// RawEvent mirrors the C struct event from tracer.c.
// Field order and sizes must match exactly.
//
// NOTE: TID is the kernel thread id (low 32 bits of pid_tgid), NOT the parent
// PID — the eBPF program has no portable way to read the real parent without
// CO-RE. Process lineage is resolved in userspace instead (see Event.Ancestry).
type RawEvent struct {
	PID         uint32
	TID         uint32
	UID         uint32
	EventType   uint8
	_           [3]byte  // padding
	Comm        [16]byte
	Filename    [128]byte
	DPort       uint16
	_           [2]byte  // padding
	DAddr       uint32
	TimestampNS uint64
	Arg1        uint64 // openat flags / ptrace request / bpf cmd
	Arg2        uint64 // ptrace target pid
}

// Event is the enriched, parsed event with container + lineage context.
type Event struct {
	PID         uint32
	TID         uint32
	UID         uint32
	Type        uint8
	ProcessName string
	Filename    string
	DstPort     uint16
	DstIP       net.IP
	Timestamp   time.Time

	// Generic per-syscall scalars (semantics depend on Type):
	//   open   → Arg1 = open flags
	//   ptrace → Arg1 = request, Arg2 = target pid
	//   bpf    → Arg1 = bpf command
	Arg1 uint64
	Arg2 uint64

	// Process lineage and command line, resolved in userspace from /proc for
	// monitored container execve events (empty otherwise). Ancestry lists the
	// parent process comm names, immediate parent first.
	Ancestry []string
	Args     []string
	CmdLine  string

	// Container context (nil if host process)
	Container *container.Info
}

func (e *Event) TypeName() string {
	switch e.Type {
	case EventExecve:
		return "execve"
	case EventOpen:
		return "open"
	case EventConnect:
		return "connect"
	case EventClone:
		return "clone"
	case EventPtrace:
		return "ptrace"
	case EventModule:
		return "init_module"
	case EventBPF:
		return "bpf"
	default:
		return "unknown"
	}
}

// Collector loads the eBPF program and streams events to a channel.
type Collector struct {
	cfg    *config.Config
	mapper *container.Mapper
	objs   tracerObjects // generated by go:generate / bpf2go
	links  []link.Link
	reader *ringbuf.Reader

	// Observability counters (see Stats).
	channelDrops       atomic.Uint64
	enrichMissArgv     atomic.Uint64
	enrichMissAncestry atomic.Uint64
}

// Stats is a point-in-time snapshot of collector health counters. Event loss
// (kernel ring-buffer overflow or userspace channel overflow) is surfaced here
// so it is visible rather than silent.
type Stats struct {
	KernelDrops        uint64 // ring-buffer reservation failures (kernel side)
	ChannelDrops       uint64 // events dropped because the userspace channel was full
	EnrichMissArgv     uint64 // execve events where /proc/<pid>/cmdline was unavailable
	EnrichMissAncestry uint64 // execve events where parent lineage was unavailable
}

// Stats returns the current counters, reading the kernel drop counter from its
// eBPF map.
func (c *Collector) Stats() Stats {
	var kernelDrops uint64
	if c.objs.Dropcount != nil {
		var key uint32
		_ = c.objs.Dropcount.Lookup(&key, &kernelDrops)
	}
	return Stats{
		KernelDrops:        kernelDrops,
		ChannelDrops:       c.channelDrops.Load(),
		EnrichMissArgv:     c.enrichMissArgv.Load(),
		EnrichMissAncestry: c.enrichMissAncestry.Load(),
	}
}

// New creates a Collector but does not start it yet.
func New(cfg *config.Config, mapper *container.Mapper) *Collector {
	return &Collector{
		cfg:    cfg,
		mapper: mapper,
	}
}

// Start loads the eBPF program into the kernel and starts the event loop.
// Events are sent to the returned channel. The channel is closed when Stop() is called.
func (c *Collector) Start() (<-chan Event, error) {
	// Remove kernel memory lock limit (required for eBPF maps)
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("remove memlock: %w", err)
	}

	// Load the eBPF spec, then apply the configured ring-buffer size before
	// loading into the kernel (KW_EBPF_RINGBUF_SIZE — must be a power of two and
	// a multiple of the page size, else the kernel rejects the map).
	spec, err := loadTracer()
	if err != nil {
		return nil, fmt.Errorf("load eBPF spec: %w", err)
	}
	if c.cfg.EBPFRingbufSize > 0 {
		if m := spec.Maps["events"]; m != nil {
			m.MaxEntries = uint32(c.cfg.EBPFRingbufSize)
		}
	}
	if err := spec.LoadAndAssign(&c.objs, nil); err != nil {
		return nil, fmt.Errorf("load eBPF objects: %w", err)
	}

	// Attach tracepoints
	tps := []struct {
		group   string
		name    string
		program *ebpf.Program
	}{
		{"syscalls", "sys_enter_execve", c.objs.TraceExecve},
		{"syscalls", "sys_enter_openat", c.objs.TraceOpenat},
		{"syscalls", "sys_enter_connect", c.objs.TraceConnect},
		{"syscalls", "sys_enter_clone", c.objs.TraceClone},
		{"syscalls", "sys_enter_ptrace", c.objs.TracePtrace},
		{"syscalls", "sys_enter_init_module", c.objs.TraceInitModule},
		{"syscalls", "sys_enter_finit_module", c.objs.TraceFinitModule},
		{"syscalls", "sys_enter_bpf", c.objs.TraceBpf},
	}

	// Attach tracepoints resiliently: a single tracepoint missing on an unusual
	// kernel should degrade coverage, not take the whole monitor down. We only
	// hard-fail if NONE attach (eBPF effectively unavailable).
	for _, tp := range tps {
		l, err := link.Tracepoint(tp.group, tp.name, tp.program, nil)
		if err != nil {
			slog.Warn("tracepoint attach failed, continuing without it",
				"tracepoint", tp.group+"/"+tp.name, "err", err)
			continue
		}
		c.links = append(c.links, l)
	}
	if len(c.links) == 0 {
		c.cleanup()
		return nil, fmt.Errorf("no tracepoints could be attached")
	}

	// Open ring buffer reader
	rd, err := ringbuf.NewReader(c.objs.Events)
	if err != nil {
		c.cleanup()
		return nil, fmt.Errorf("open ringbuf: %w", err)
	}
	c.reader = rd

	events := make(chan Event, 1000)
	go c.readLoop(events)

	slog.Info("eBPF collector started",
		"tracepoints_attached", len(c.links),
		"tracepoints_total", len(tps),
		"ringbuf_size", c.cfg.EBPFRingbufSize,
	)

	return events, nil
}

// Stop detaches eBPF programs and closes the ring buffer.
func (c *Collector) Stop() {
	if c.reader != nil {
		c.reader.Close()
	}
	c.cleanup()
}

func (c *Collector) cleanup() {
	for _, l := range c.links {
		l.Close()
	}
	c.objs.Close()
}

// readLoop reads raw events from the ring buffer, parses and enriches them,
// and sends them to the events channel.
func (c *Collector) readLoop(out chan<- Event) {
	defer close(out)

	for {
		record, err := c.reader.Read()
		if err != nil {
			// Reader closed — normal shutdown
			return
		}

		var raw RawEvent
		if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &raw); err != nil {
			slog.Debug("parse raw event", "err", err)
			continue
		}

		event := c.parseEvent(raw)

		// Resolve container context
		info, err := c.mapper.Resolve(event.PID)
		if err != nil {
			slog.Debug("resolve container", "pid", event.PID, "err", err)
		}
		event.Container = info

		// Filter: skip if container is not monitored
		if info != nil && !c.cfg.IsMonitored(info.Name) {
			continue
		}

		// Skip noisy open events for known system paths
		if event.Type == EventOpen && isNoisyPath(event.Filename) {
			continue
		}

		// Enrich monitored container events with lineage + argv, but only for the
		// low-frequency, high-signal syscalls — never for open/connect (the extra
		// /proc reads would run for every file access).
		if info != nil && needsEnrichment(event.Type) {
			event.Ancestry = container.ResolveAncestry(event.PID, c.cfg.AncestryDepth)
			event.Args, event.CmdLine = readCmdline(event.PID)
			// Track enrichment misses (process exited before /proc read) so the
			// lineage/argv coverage rate is observable.
			if event.CmdLine == "" {
				c.enrichMissArgv.Add(1)
			}
			if len(event.Ancestry) == 0 {
				c.enrichMissAncestry.Add(1)
			}
		}

		select {
		case out <- event:
		default:
			// Channel full — drop and count. Warn rate-limited to avoid log floods.
			if n := c.channelDrops.Add(1); n%100 == 1 {
				slog.Warn("event channel full, dropping events", "dropped_total", n)
			}
		}
	}
}

func (c *Collector) parseEvent(raw RawEvent) Event {
	e := Event{
		PID:         raw.PID,
		TID:         raw.TID,
		UID:         raw.UID,
		Type:        raw.EventType,
		ProcessName: cstring(raw.Comm[:]),
		Filename:    cstring(raw.Filename[:]),
		DstPort:     raw.DPort,
		Timestamp:   time.Unix(0, int64(raw.TimestampNS)),
		Arg1:        raw.Arg1,
		Arg2:        raw.Arg2,
	}

	if raw.DAddr != 0 {
		ip := make(net.IP, 4)
		binary.LittleEndian.PutUint32(ip, raw.DAddr)
		e.DstIP = ip
	}

	return e
}

// readCmdline reads /proc/<pid>/cmdline (NUL-separated argv) and returns the
// argument vector plus a space-joined command line.
//
// At sys_enter_execve the event is queued before the exec completes; by the
// time we read here the new image is normally loaded, so cmdline reflects the
// executed command (e.g. "bash -c <payload>"). Best-effort: an ultra-short-lived
// process may already be gone, in which case callers fall back to Filename.
func readCmdline(pid uint32) (args []string, cmdline string) {
	data, err := os.ReadFile(fmt.Sprintf("/proc/%d/cmdline", pid))
	if err != nil || len(data) == 0 {
		return nil, ""
	}
	parts := bytes.Split(data, []byte{0})
	args = make([]string, 0, len(parts))
	for _, p := range parts {
		if len(p) > 0 {
			args = append(args, string(p))
		}
	}
	return args, strings.Join(args, " ")
}

// needsEnrichment reports whether an event type warrants the per-event /proc
// reads for ancestry + argv. Limited to low-frequency, high-signal syscalls.
func needsEnrichment(eventType uint8) bool {
	switch eventType {
	case EventExecve, EventPtrace, EventModule, EventBPF:
		return true
	default:
		return false
	}
}

// cstring converts a null-terminated byte slice to a Go string.
func cstring(b []byte) string {
	if idx := bytes.IndexByte(b, 0); idx != -1 {
		b = b[:idx]
	}
	return string(b)
}

// isNoisyPath returns true for high-frequency paths that are rarely security-relevant.
func isNoisyPath(path string) bool {
	noisyPrefixes := []string{
		"/proc/",
		"/sys/",
		"/dev/null",
		"/dev/urandom",
		"/etc/localtime",
		"/usr/share/zoneinfo",
	}
	for _, prefix := range noisyPrefixes {
		if len(path) >= len(prefix) && path[:len(prefix)] == prefix {
			return true
		}
	}
	return false
}
