package collector

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"log/slog"
	"net"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"

	"containersentry/internal/config"
	"containersentry/internal/container"
)

// Event types — must match EVENT_* constants in tracer.c
const (
	EventExecve  = 1
	EventOpen    = 2
	EventConnect = 3
	EventClone   = 4
)

// RawEvent mirrors the C struct event from tracer.c.
// Field order and sizes must match exactly.
type RawEvent struct {
	PID         uint32
	PPID        uint32
	UID         uint32
	EventType   uint8
	_           [3]byte  // padding
	Comm        [16]byte
	Filename    [128]byte
	DPort       uint16
	_           [2]byte  // padding
	DAddr       uint32
	TimestampNS uint64
}

// Event is the enriched, parsed event with container context.
type Event struct {
	PID         uint32
	PPID        uint32
	UID         uint32
	Type        uint8
	ProcessName string
	Filename    string
	DstPort     uint16
	DstIP       net.IP
	Timestamp   time.Time

	// Container context (nil if host process)
	Container *container.Info
}

func (e *Event) TypeName() string {
	switch e.Type {
	case EventExecve:
		return "execve"
	case EventOpen:
		return "open"
	case EventConnect:
		return "connect"
	case EventClone:
		return "clone"
	default:
		return "unknown"
	}
}

// Collector loads the eBPF program and streams events to a channel.
type Collector struct {
	cfg    *config.Config
	mapper *container.Mapper
	objs   tracerObjects // generated by go:generate / bpf2go
	links  []link.Link
	reader *ringbuf.Reader
}

// New creates a Collector but does not start it yet.
func New(cfg *config.Config, mapper *container.Mapper) *Collector {
	return &Collector{
		cfg:    cfg,
		mapper: mapper,
	}
}

// Start loads the eBPF program into the kernel and starts the event loop.
// Events are sent to the returned channel. The channel is closed when Stop() is called.
func (c *Collector) Start() (<-chan Event, error) {
	// Remove kernel memory lock limit (required for eBPF maps)
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("remove memlock: %w", err)
	}

	// Load the compiled eBPF object (generated by bpf2go)
	if err := loadTracerObjects(&c.objs, &ebpf.CollectionOptions{
		Maps: ebpf.MapOptions{
			// Override ring buffer size from config
			PinPath: "",
		},
	}); err != nil {
		return nil, fmt.Errorf("load eBPF objects: %w", err)
	}

	// Attach tracepoints
	tps := []struct {
		group   string
		name    string
		program *ebpf.Program
	}{
		{"syscalls", "sys_enter_execve", c.objs.TraceExecve},
		{"syscalls", "sys_enter_openat", c.objs.TraceOpenat},
		{"syscalls", "sys_enter_connect", c.objs.TraceConnect},
		{"syscalls", "sys_enter_clone", c.objs.TraceClone},
	}

	for _, tp := range tps {
		l, err := link.Tracepoint(tp.group, tp.name, tp.program, nil)
		if err != nil {
			c.cleanup()
			return nil, fmt.Errorf("attach tracepoint %s/%s: %w", tp.group, tp.name, err)
		}
		c.links = append(c.links, l)
	}

	// Open ring buffer reader
	rd, err := ringbuf.NewReader(c.objs.Events)
	if err != nil {
		c.cleanup()
		return nil, fmt.Errorf("open ringbuf: %w", err)
	}
	c.reader = rd

	events := make(chan Event, 1000)
	go c.readLoop(events)

	slog.Info("eBPF collector started",
		"tracepoints", len(tps),
		"ringbuf_size", c.cfg.EBPFRingbufSize,
	)

	return events, nil
}

// Stop detaches eBPF programs and closes the ring buffer.
func (c *Collector) Stop() {
	if c.reader != nil {
		c.reader.Close()
	}
	c.cleanup()
}

func (c *Collector) cleanup() {
	for _, l := range c.links {
		l.Close()
	}
	c.objs.Close()
}

// readLoop reads raw events from the ring buffer, parses and enriches them,
// and sends them to the events channel.
func (c *Collector) readLoop(out chan<- Event) {
	defer close(out)

	for {
		record, err := c.reader.Read()
		if err != nil {
			// Reader closed — normal shutdown
			return
		}

		var raw RawEvent
		if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &raw); err != nil {
			slog.Debug("parse raw event", "err", err)
			continue
		}

		event := c.parseEvent(raw)

		// Resolve container context
		info, err := c.mapper.Resolve(event.PID)
		if err != nil {
			slog.Debug("resolve container", "pid", event.PID, "err", err)
		}
		event.Container = info

		// Filter: skip if container is not monitored
		if info != nil && !c.cfg.IsMonitored(info.Name) {
			continue
		}

		// Skip noisy open events for known system paths
		if event.Type == EventOpen && isNoisyPath(event.Filename) {
			continue
		}

		select {
		case out <- event:
		default:
			// Channel full — drop and warn
			slog.Warn("event channel full, dropping event")
		}
	}
}

func (c *Collector) parseEvent(raw RawEvent) Event {
	e := Event{
		PID:         raw.PID,
		PPID:        raw.PPID,
		UID:         raw.UID,
		Type:        raw.EventType,
		ProcessName: cstring(raw.Comm[:]),
		Filename:    cstring(raw.Filename[:]),
		DstPort:     raw.DPort,
		Timestamp:   time.Unix(0, int64(raw.TimestampNS)),
	}

	if raw.DAddr != 0 {
		ip := make(net.IP, 4)
		binary.LittleEndian.PutUint32(ip, raw.DAddr)
		e.DstIP = ip
	}

	return e
}

// cstring converts a null-terminated byte slice to a Go string.
func cstring(b []byte) string {
	if idx := bytes.IndexByte(b, 0); idx != -1 {
		b = b[:idx]
	}
	return string(b)
}

// isNoisyPath returns true for high-frequency paths that are rarely security-relevant.
func isNoisyPath(path string) bool {
	noisyPrefixes := []string{
		"/proc/",
		"/sys/",
		"/dev/null",
		"/dev/urandom",
		"/etc/localtime",
		"/usr/share/zoneinfo",
	}
	for _, prefix := range noisyPrefixes {
		if len(path) >= len(prefix) && path[:len(prefix)] == prefix {
			return true
		}
	}
	return false
}
